on:
  push:
    branches:
      - main

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: tool-chain for macos
        if : ${{ matrix.os == 'macos-latest' }}
        run: |
          rustup target add x86_64-apple-darwin
      
      - name: toolchain for linux
        if : ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          cargo install cross --git https://github.com/cross-rs/cross


      - name: Build
        run: |
          cd src/pairwriter_helper 
          npm install
          python3 os_specific_compile.py

      - name: Add Changes
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add -A 
          git commit -m "compiled" || echo "No changes to commit"
          git push -u origin HEAD:${{ matrix.os }}-prerelease

  merge:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Merge Changes
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git fetch
          git branch -r
          git checkout releases || git checkout -b releases
          git merge origin/ubuntu-latest-prerelease || echo "No changes to merge"
          git merge origin/macos-latest-prerelease || echo "No changes to merge"
          git merge origin/windows-latest-prerelease || echo "No changes to merge"
          git push origin releases -f

  remove-artifacts:
    needs: merge
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - name: Remove windows
        run: |
          gh api -X DELETE /repos/m10090/pairwriter-vsc/git/refs/heads/windows-latest-prerelease
          gh api -X DELETE /repos/m10090/pairwriter-vsc/git/refs/heads/macos-latest-prerelease
          gh api -X DELETE /repos/m10090/pairwriter-vsc/git/refs/heads/ubuntu-latest-prerelease
