on:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: |
          cd src/pairwriter_helper 
          python3 os_specific_compile.py

      - name: Add Changes
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add -A 
          git push -u origin ${{ matrix.os }}-prerelease

  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Merge Changes
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git checkout releases || git checkout -b releases
          git pull origin releases
          git merge ubuntu-latest-prerelease || echo "No changes to merge"
          git merge macos-latest-prerelease || echo "No changes to merge"
          git merge windows-latest-prerelease || echo "No changes to merge"
          git push origin releases
